# Generated by Django 3.1 on 2020-09-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_group'),
        ('groups', '0002_coursegroup_is_ended'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
