# Generated by Django 3.1 on 2020-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
