# Generated by Django 3.1 on 2020-08-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('materials', models.FileField(default=None, upload_to='lessons_materials/')),
                ('path_to_video_lesson', models.CharField(default='', max_length=255)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.coursegroup')),
            ],
        ),
    ]
