# Generated by Django 3.1 on 2020-09-02 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200902_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='planning_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
