# Generated by Django 3.1 on 2020-09-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
            preserve_default=False,
        ),
    ]
